-- Create Admin User for Testing
-- Password: admin123 (hashed dengan bcrypt cost 10)

-- First, check if admin user exists
SELECT * FROM users WHERE username = 'admin' OR user_id = 'AD0001';

-- If not exists, insert admin user
-- Note: Password 'admin123' hashed with bcrypt cost 10
INSERT INTO users (username, user_id, password, role, operator, is_active, created_at, updated_at)
VALUES (
    'Jeremy Agape',
    'PI0824.2374',
    '$2a$10$YourHashedPasswordHere', -- This is placeholder, actual hash will be generated by backend
    'Admin',
    'Administrator',
    true,
    NOW(),
    NOW()
)
ON CONFLICT (username) DO NOTHING;

-- Alternatively, update existing user to admin
-- UPDATE users SET role = 'Admin' WHERE username = 'jeremyakamsi';

-- Check existing users
SELECT id, username, user_id, role, operator, is_active, created_at 
FROM users 
ORDER BY created_at DESC;
